Feature/4 list homework
MaxPirojkov/mtsteta pull request #2
Opened 2021-07-20 18:30 UTC by MaxPirojkov

рейтинг реализовал через ratingbar. когда менял звезды, черные накладывались на белые. поэтому оставил нативные

2021-07-20 19:14 UTC, NikolayUkhvarov requested changes

2021-07-20 19:14 UTC, NikolayUkhvarov commented on app/src/main/java/com/mtsteta/android/pirozhkovteta/PreviewMovieAdapter.kt
> +    val movies: List<PreviewMovie>,
нужно убрать из адаптера и передавать отдельно

2021-07-20 19:14 UTC, NikolayUkhvarov commented on app/build.gradle
> +        viewBinding true
а где это используется?

2021-07-20 19:20 UTC, MaxPirojkov commented on app/build.gradle
> +        viewBinding true
забыл удалить. уберу

2021-07-22 07:09 UTC, NikolayUkhvarov requested changes

2021-07-22 07:09 UTC, NikolayUkhvarov commented on app/src/main/java/com/mtsteta/android/pirozhkovteta/PreviewMovieAdapter.kt
> +    private val clickListener: MainActivity
это плохо
передай экземпляр функции, тогда не будет двух реализация клика в активити и адаптере

2021-07-22 10:42 UTC, NikolayUkhvarov approved these changes

2021-07-22 10:44 UTC, merged